### ISSUE TITLE
"rollback transaction" when I try to add a new campaign

### ISSUE THREAD

**Issue by cesarediaz** [Wirelab-archive/refinerycms-mailchimp#10]
I have added this engine and every time that I add a new campaign  I see this message in admin side "'Campaign one' was successfully added." but there is not new campaign added... If I see what happens in log file

Started POST "/refinery/campaigns" for 127.0.0.1 at 2012-06-11 18:33:44 -0300
Processing by Refinery::Mailchimp::Admin::CampaignsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"k907kw87kj7890wjkw875kw897234kjlwa=", "campaign"=>{"subject"=>"Campaign one", "bo"=>"good, we have the solution!!", "to_name"=>"one", "from_name"=>"one", "from_email"=>"info@one.com", "mailchimp_list_id"=>"28
c9bc19ad", "mailchimp_template_id"=>"11037.0", "auto_tweet"=>"0"}, "locale"=>:en}
  ESC[1mESC[35mRefinery::Role Load (0.3ms)ESC[0m  SELECT "refinery_roles".\* FROM "refinery_roles" WHERE "refinery_roles"."title" = 'Refinery' LIMIT 1
  ESC[1mESC[36mRefinery::User Load (0.8ms)ESC[0m  ESC[1mSELECT "refinery_users".\* FROM "refinery_users" INNER JOIN "refinery_roles_users" ON "refinery_users"."id" = "refinery_roles
_users"."user_id" WHERE "refinery_roles_users"."role_id" = 1ESC[0m
  ESC[1mESC[35mRefinery::User Load (0.4ms)ESC[0m  SELECT "refinery_users".\* FROM "refinery_users" WHERE "refinery_users"."id" = 1 LIMIT 1
  ESC[1mESC[36mRefinery::UserPlugin Load (0.4ms)ESC[0m  ESC[1mSELECT "refinery_user_plugins".\* FROM "refinery_user_plugins" WHERE "refinery_user_plugins"."user_id" = 1 ORDER BY pos
ition ASCESC[0m
  ESC[1mESC[35mRefinery::Role Load (0.3ms)ESC[0m  SELECT "refinery_roles".\* FROM "refinery_roles" INNER JOIN "refinery_roles_users" ON "refinery_roles"."id" = "refinery_roles_users
"."role_id" WHERE "refinery_roles_users"."user_id" = 1
  ESC[1mESC[36m (0.2ms)ESC[0m  ESC[1mbegin transactionESC[0m
  ESC[1mESC[35m (0.2ms)ESC[0m  rollback transaction
Redirected to http://0.0.0.0:3000/refinery/campaigns
Completed 302 Found in 2771ms (ActiveRecord: 2.5ms)

at the last part of this log I can see this ... 'rollback transaction' but I don't have a clue about what is causing this rollback

**Comment by johanb** [comment]
Could you elaborate on a few things:
- Which version of RefineryCMS are you using ?
- Which version of Rails are you using ?
- Have you set the API key and do you have the correct permissions ?

I'll try to look into it for you. 

Please note: 2.0 is still in development and bugs are a plenty. We hope to release the final 2.0 version soon though.

**Comment by johanb** [comment]
I've investigated the issue and am able to reproduce it.

Step 1: Install clean refinerycms
Step 2: Follow install instruction of this gem
Step 3: Create a campaign with some 'bogus' data

The application will incorrectly state that the campaign has been created. In fact the Hominid call will have failed and will have returned an error. The API call made to Mailchimp is currently performed in an AR Hook, which in my opinion is ugly and error prone.

One of the example error messages returned from the API looks like: 

"<311> from_email - This email address looks fake or invalid. Please enter a real email address" (when testing with test@test.nl)

I'm investigating possible solutions, pull requests and suggestions are welcome.

**Comment by johanb** [comment]
So this issue is related to issue #6

**Comment by cesarediaz** [comment]
Better late than never:

Data about my working environment:
- refinerycms (2.0.4)
- rails (3.2.3)
- about your question "Have you set the API key and do you have the correct permissions ?" : I think that have setup it properly. 

This was happening in development mode and on Heroku 'staging' environment

Now I have tested again but on 'production' environment and this works fine!

Many thanks by your work!

Greetings!
