### ISSUE TITLE
Repository not found error when installing

### ISSUE THREAD

**Issue by tommaxwell** [Wirelab-archive/refinerycms-mailchimp#17]
I added the appropriate gem to my Gemfile -- the same one in the README, and I'm getting the following error on bundle install:

Fetching git://github.com/Wirelab/refinerycms-mailchimp.git
fatal: remote error: 
  Repository not found.
Git error: command `git clone
'git://github.com/Wirelab/refinerycms-mailchimp.git'
"/home/tom/.rvm/gems/ruby-1.9.3-p429/cache/bundler/git/refinerycms-mailchimp-2ae5de07b00fe624b0abd25a2f58575876229dce"
--bare --no-hardlinks` in directory /home/tom/chakra_blog has failed.

I've had no trouble adding other Refinery engines.

**Comment by johanb** [comment]
Hi @tommaxwell sorry for my way way way to late reply. Are you still having this problem ? The only thing I can imagine wrong is that you've written `Wirelab` with a capital `W` instead of a lowercase `wirelab`.
