### ISSUE TITLE
Refinerycms-mailchimp

### ISSUE THREAD

**Issue by deepaktyagi3i36** [Wirelab-archive/refinerycms-mailchimp#5]
"ianterrell / refinerycms-mailchimp" this is not working well. it is not creating new campaign on local database.
it just create untitled campaign on mailchimp site. can someone help me??

**Comment by deepaktyagi3i36** [comment]
there is no error on creating the campaign on local machine, it gives the flash message that "<campaign_subject> was successfully created". but it is not creating it in local database.

**Comment by ghost** [comment]
Am experiencing the same issue. It is a wonderful enhancement to the refinerycms. I wish I were capable of fixing it myself, but I'm not, and I would really like to see this working. If you have a wishlist, I would gladly contribute.

**Comment by ianterrell** [comment]
I'm unable to reproduce this issue.

The gem was developed and tested to work fine against Ruby 1.8.7, Rails 3.0.5, and Refinery 0.9.9.15. I've just upgraded everything and tested again, and it works for me with Ruby 1.9.2, Rails 3.0.10, and Refinery 1.0.8.
